@startuml
package client {
    class ManaRequestBody{
        Attachments: Dictionary<string, string>
        Locations: IEnumerable<GpsLocation>
        UploadFiles: IEnumerable<AccessInfo>
        Form: JsonElement
    }
}

package Server {
    class "ManaRequestBody<T>" {
        Attachments: Dictionary<string, string>
        Locations: IEnumerable<GpsLocation>
        UploadFiles: IEnumerable<AccessInfo>
        Form: T
    }
}
@enduml