@startuml
package Issuers {
    node manaclient
    cloud manaapi
}

package DB {
    database Home
    database Cart
    database Order
    database Form

    Home -[hidden]- Cart
    Cart -[hidden]- Order
    Order -[hidden]- Form
}

package FeedService {
    [FeedService<Home>]
    [FeedService<Cart>]
    
    [FeedService<Home>] -[hidden]- [FeedService<Cart>]
}

package FeedReceiver {
    [FeedReceiver<Home>] <<FunctionApp>>
    [FeedReceiver<Cart>]

    [FeedReceiver<Home>] -[hidden]- [FeedReceiver<Cart>]
}

package client {
    cloud 3rdapi
    ' manaclient -[hidden]- 3rdapi
}

manaclient -> manaapi : 0. some action

' manaapi -> Home : 1. create homefeed
' manaapi -> [FeedService<Home>] : 2. send hook
' Home <- [FeedService<Home>] : 3. get data
' [FeedService<Home>] -> [FeedReceiver<Home>] : 4. notify hook
' [FeedService<Home>] <- [FeedReceiver<Home>] : 5. feed data
' [FeedReceiver<Home>] -> manaclient : 6. notification / signalR

manaapi -> Cart : 1. create cart
manaapi -> [FeedService<Cart>] : 2. send hook
Cart <- [FeedService<Cart>] : 3. get data
[FeedService<Cart>] -> [FeedReceiver<Cart>] : 4. notify hook
[FeedService<Cart>] <- [FeedReceiver<Cart>] : 5. feed data
[FeedReceiver<Cart>] -> 3rdapi : 6. cart data

@enduml