@startuml ManaGate

!include ColorMeaning.puml

package ManaGate {
    [TheGatel] #LightGreen
    [TheaCEmb] #LightGreen

    [ManaGate-p] #LightYellow
    note right
        devN
        devmaster
        testflight
        release
        production
    end note

    [TheGatel] --> [ManaGate-p]
    [TheaCEmb] --> [ManaGate-p]

    [managate] #Orange
    [manacemb] #Orange

    [ManaGate-p] --> [managate]
    [ManaGate-p] --> [manacemb]
}

@enduml