@startuml ManaIdp

!include ColorMeaning.puml

package ManaService {
    [IdpDaddy] #LightGreen

    [ManaIdp-p] #LightYellow
    note right
        devmaster
        + devN
        testflight
        + release
        production
    end note

    [IdpDaddy] --> [ManaIdp-p]

    [manaidp] #Orange

    [ManaIdp-p] --> [manaidp]
}

@enduml