@startuml dev-and-prod

[AmloSand] <<SANDBOX>>
note bottom of [AmloSand]
@@@ ideas ในอุดมคติ @@@
AmloDev ทดลอง sync กับ AmloSand

@@@ ที่จะทำ @@@
AmloSand AmloReal
request/response บางอย่างไม่เหมือนกัน
ใน dev เลยจะไม่ทำ sync กับ AmloSand
จะทำเป็น request/response ธรรมดา
end note

package DevCluster {
    cloud {
        [DevA]
        [DevB]
        [DevC]
        [DevD]
        [DevX]
    }
    [DevMaster]

    [AmloDev] <<MOCK>>
    [DopaDev] <<MOCK>>
    [P2DDev] <<MOCK>>
    [FraudDev]
    [InsightDev]

    [DevMaster] . [AmloDev]
    [AmloDev] . [AmloSand]
    [DevMaster] .. [DopaDev]
    [DevMaster] .. [P2DDev]
    [DevMaster] ... [FraudDev]
    [FraudDev] <-l- [InsightDev]

    [AmloDev] .[hidden]. [DopaDev]
    [DopaDev] .[hidden]. [P2DDev]

    [DevMaster] .[hidden]... [DevA]
}

package PreCluster {
    [Testflight]

    [AmloPre] <<MOCK>>
    [DopaPre] <<MOCK>>
    [P2DPre] <<MOCK>>
    [FraudPre]
    [InsightPre]

    [Testflight] . [AmloPre]
    [AmloPre] . [AmloSand]
    [Testflight] . [DopaPre]
    [Testflight] . [P2DPre]
    [Testflight] ... [FraudPre]
    [FraudPre] <-l- [InsightPre]

    [AmloPre] .[hidden]. [DopaPre]
    [DopaPre] .[hidden]. [P2DPre]
}

[Amlo] <<REAL>>
[Dopa] <<REAL>>
[P2D] <<REAL>>

package ProdCluster {
    cloud {
        [Staging]
    }
    [Production]
    [AmloProd]
    [DopaProd]
    [FraudProd]
    [InsightProd]

    [Production] .[hidden].. [Staging]
    [Production] .. [FraudProd]
    [FraudProd] <-l- [InsightProd]
}

[Production] . [AmloProd]
[AmloProd] . [Amlo]
[Production] .. [DopaProd]
[DopaProd] . [Dopa]
[Production] ... [P2D]

@enduml