@startuml kyc

participant client
participant api
participant backoffice
participant idp
participant dopa
database temp
database kyc

client -> api : submit
activate client
api -> temp : upload
client <-- api : confirmation
deactivate client

client -> api : confirm
activate client
api -> backoffice : send
activate backoffice
client <- api : msg wait
deactivate client

alt #LawnGreen
    backoffice -> dopa : validate
    backoffice <-- dopa : validate result
    backoffice -> backoffice : update status to db
end

api <- backoffice : approve
api -> temp : read
api -> idp : record
idp -> temp : read
idp -> kyc : upload
client <-- api : noti
api --> backoffice : approved
deactivate backoffice

@enduml