@startuml kyc

participant client
participant api
participant backoffice
participant idp
queue "validate\nqueue"
participant "dopaService\nwiremock"
participant dopa
database temp
database kyc

client -> api : submit
activate client
api -> temp : upload
client <-- api : confirmation
deactivate client

client -> api : confirm
activate client
api -> backoffice : send
activate backoffice
client <- api : msg wait
deactivate client

alt #LawnGreen
    backoffice -> "validate\nqueue" : queue
    deactivate backoffice
    "validate\nqueue" --> "dopaService\nwiremock" : dequeue
    activate "dopaService\nwiremock"
    loop #LawnGreen
        "dopaService\nwiremock" -> dopa : validate
        backoffice <- "dopaService\nwiremock" : update result
        activate backoffice
    end
    deactivate "dopaService\nwiremock"
end

api <- backoffice : approve
api -> temp : read
api -> idp : record
idp -> temp : read
idp -> kyc : upload
client <-- api : noti
api --> backoffice : approved

@enduml