@startuml ManaRequestBody

!define COMMENT(x) <color:darkgreen>x</color>

package TheS.Mana.Shared.Models {
    class GeoLocation {
        Latitude: double
        Longitude: double
    }
    class DeliveryGeoLocation extends GeoLocation {
        Remark: string
        PhoneNumber: string
    }
    class LogisticGeoLocation extends DeliveryGeoLocation {
        Address: AddressInfo
    }
    class AccessInfo { }
    AccessInfo -l- LogisticGeoLocation
}

package Client {
    class ManaRequestBody {
        Attachments: AccessInfo
        Locations: IEnumerable<GeoLocation>
        ExData: Dictionary<string, string> COMMENT(// quantity employeeid consent dontshowmeagain?)
        Form: JsonElement
    }
    ' GeoLocation -- ManaRequestBody
    ' AccessInfo -- ManaRequestBody
}

package Server {
    class "ManaRequestBody<T>" {
        Attachments: AccessInfo
        Locations: IEnumerable<GeoLocation>
        ExData: Dictionary<string, string>
        Form: T
    }
    ' GeoLocation -- "ManaRequestBody<T>"
    ' AccessInfo -- "ManaRequestBody<T>"
}
Client -[hidden]- Server

@enduml