@startuml ManaRequestBody

!define COMMENT(x) <color:darkgreen>x</color>

package TheS.Mana.Shared.Models {
    class GeoLocation {
        Latitude: double
        Longitude: double
        COMMENT(// Remark)
        COMMENT(// PhoneNumber)
    }
    class AccessInfo { }
}

package client {
    class ManaRequestBody {
        Attachments: AccessInfo
        Locations: IEnumerable<GeoLocation>
        ExData: Dictionary<string, string> COMMENT(// quantity employeeid consent dontshowmeagain?)
        Form: JsonElement
    }
    GeoLocation -- ManaRequestBody
    AccessInfo -- ManaRequestBody

    ' class GetApiData_Header {
    '     lat: double
    '     lon: double
    ' }
    ' ManaRequestBody -[hidden]- GetApiData_Header

    ' class MContentServerUrl_Header {
    '     lat: double
    '     lon: double
    ' }
    ' ManaRequestBody -[hidden]- MContentServerUrl_Header
}

package Server {
    class "ManaRequestBody<T>" {
        Attachments: AccessInfo
        Locations: IEnumerable<GeoLocation>
        ExData: Dictionary<string, string>
        Form: T
    }
    GeoLocation -- "ManaRequestBody<T>"
    AccessInfo -- "ManaRequestBody<T>"
}

@enduml