@startuml ManaRequestBody

!define COMMENT(x) <color:darkgreen>x</color>

package TheS.Mana.Shared.Models {
    class GeoLocation {
        Realm: string COMMENT(// SubDistrict + District + Province)
        Latitude: double
        Longitude: double
        Accuracy: double?
    }
    class Address {
        Title: string
        StreetAddress: string
        SubDistrict: string
        District: string
        Province: string
        PostalCode: string
        PhoneNumber: string
        Remark: string
    }

    class GpsSection {
        COMMENT(// Title = Realm)
        Title: string
        GeoLocation: GeoLocation
    }
    GeoLocation <-- GpsSection
    class GpsLocation {
        COMMENT(// Title = Realm + Remark + PhoneNumber)
        Remark: string
        PhoneNumber: string
    }
    GpsSection <|-l GpsLocation
    class GpsAddress {
        COMMENT(// Title = Address: Title+Remark+PhoneNumber)
        Address: Address
    }
    GpsSection <|- GpsAddress
    Address <-- GpsAddress
}

package Client {
    class ManaRequestBody {
        Attachments: AccessInfo
        Locations: IEnumerable<GpsSection>
        COMMENT(// quantity employeeid consent dontshowmeagain?)
        ExData: Dictionary<string, string>
        Form: JsonElement
    }
}

package Server {
    class "ManaRequestBody<T>" {
        Attachments: AccessInfo
        Locations: IEnumerable<GpsSection>
        ExData: Dictionary<string, string>
        Form: T
    }
}
Client -[hidden]- Server

@enduml