@startuml sequence

participant client
participant api

== GetApiData ==

client -> api : [GET] https://mana.com/mct/data/some-page/nxxxyyy-123
note right
headers: {
    location1: Latitude=1.111&Longitude=1.111&Accuracy=11.123
    location2: Latitude=2.222&Longitude=2.222&Accuracy=11.123
}
endnote
client <-- api : [data]

== Submit ==

client -> api : [POST] https://mana.com/mct/data/some-page/nxxxyyy-123
note right
headers: {
    location1: Latitude=1.111&Longitude=1.111&Accuracy=11.123
    location2: Latitude=2.222&Longitude=2.222&Accuracy=11.123
}
body: {
    Attachments: {}
    Locations: []
    ExData: []
    Form: {}
}
endnote
client <-- api : [ClientResponse]

@enduml