@startuml sequence

participant client
participant api

== GetApiData ==

client -> api : [GET] https://mana.com/mct/data/some-page/nxxxyyy-123
note right
headers: {
    X-MANA-LOCATIONS: [{Latitude:27.132456,Longitude:107.123456}]
}
endnote
client <-- api : [data]

== Submit ==

client -> api : [POST] https://mana.com/mct/data/some-page/nxxxyyy-123
note right
body: {
    Attachments: {}
    Locations: []
    ExData: []
    Form: {}
}
endnote
client <-- api : [ClientResponse]

@enduml