@startuml sequence

participant client
participant api
participant 3rd

== MContent ==

client -> api : https://mana.com/mct/some-page?lat=27.132456&lon=107.123456
api -> 3rd : https://3rd.com/#/page?lat=27.132456&lon=107.123456
api <-- 3rd
client <-- api

== MContent (NEW) ==

client -> api : https://mana.com/mct/some-page/nxxxttt-123?lat=27.132456&lon=107.123456
api -> 3rd : https://3rd.com/#/page?nptid=nxxxyyy-123&lat=27.132456&lon=107.123456
api <-- 3rd
client <-- api

@enduml